uncategorized:
  plugin_cas_sso_host:
    default: 'YOUR.CAS.SERVER'
  plugin_cas_sso_port:
    default: '443'
  plugin_cas_sso_path:
    default: ''
  plugin_cas_sso_ssl:
    default: true
  plugin_cas_sso_login_url:
    default: '/login'
  plugin_cas_sso_logout_url:
    default: '/logout'
  plugin_cas_sso_service_validate_url:
    default: '/service_validate_url'
  plugin_cas_sso_uid_key:
    default: 'user'
  plugin_cas_sso_name:
    default: 'Name'
  plugin_cas_sso_email:
    default:  'UserPrincipalName'
  plugin_cas_sso_email_domain:
    default:  'YOUR.EMAIL.DOMAIN'
  plugin_cas_sso_user_approved:
    default:  true