cas_sso:
  cas_sso_url:
    default: 'https://YOUR.CAS.SERVER/cas'
  cas_sso_host:
    default: 'YOUR.CAS.SERVER'
  cas_sso_port:
    default: '443'
  cas_sso_path:
    default: ''
  cas_sso_ssl:
    default: true
  cas_sso_login_url:
    default: '/login'
  cas_sso_logout_url:
    default: '/logout'
  cas_sso_service_validate_url:
    default: '/serviceValidate'
  cas_sso_uid_field:
    default: 'user'
  cas_sso_name:
    default: 'Name'
  cas_sso_email:
    default:  'UserPrincipalName'
  cas_sso_email_domain:
    default:  'YOUR.EMAIL.DOMAIN'
  cas_sso_user_auto_create:
    default:  true
  cas_sso_user_approved:
    default:  true
  cas_sso_groups_allow_filter:
    default:  false
  cas_sso_groups_allow:
      client: true
      type: list
      default: 'CN=staff,OU=Groups,DC=example,DC=edu|CN=students,OU=Groups,DC=example,DC=edu|CN=faculty,OU=Groups,DC=example,DC=edu'
  cas_sso_groups_deny_filter:
    default:  false
  cas_sso_groups_deny:
      client: true
      type: list
      default: 'CN=staff,OU=Groups,DC=example,DC=edu|CN=students,OU=Groups,DC=example,DC=edu|CN=faculty,OU=Groups,DC=example,DC=edu'
