cas_sso:
  cas_sso_host:
    default: 'YOUR.CAS.SERVER'
  cas_sso_port:
    default: '443'
  cas_sso_path:
    default: ''
  cas_sso_ssl:
    default: true
  cas_sso_login_url:
    default: '/login'
  cas_sso_logout_url:
    default: '/logout'
  cas_sso_service_validate_url:
    default: '/service_validate_url'
  cas_sso_uid_key:
    default: 'user'
  cas_sso_name:
    default: 'Name'
  cas_sso_email:
    default:  'UserPrincipalName'
  cas_sso_email_domain:
    default:  'YOUR.EMAIL.DOMAIN'
  cas_sso_user_approved:
    default:  true